### ISSUE TITLE
Expected a command, got --openapi

### ISSUE THREAD

**Issue by floriankammermann** [knutaa/oas2puml#12]
When I run the jar like this `java -jar apidiagram-1.3.0-SNAPSHOT.jar TMF620-Product_Catalog_Management-v5.0.0.oas.yaml` I get the output `Expected a command, got --openapi`.

What is the correct command to produce the puml file?

**Comment by knutaa** [comment]
Try adding the command, i.e. diagrams.  Like this

```java -jar apidiagram-1.3.0-SNAPSHOT.jar diagrams --openapi TMF620-Product_Catalog_Management-v5.0.0.oas.yaml```

And try with one of the latest versions, 1.3.0 is by now a bit old.
